export const SET_SELECTED_CATEGORY_OF_QUESTIONS = 'SET_SELECTED_CATEGORY_OF_QUESTIONS';
export const SET_ANSWER_ON_QUESTION = 'SET_ANSWER_ON_QUESTION';
export const SET_TEST_FINISHED = 'SET_TEST_FINISHED';
export const CHECK_THE_RESULT = 'CHECK_THE_RESULT';
