export const SET_RANDOM_SEQUENCE = 'SET_RANDOM_SEQUENCE';
export const CHANGE_COLOR_IN_SEQUENSE_TO_BLACK = 'CHANGE_COLOR_IN_SEQUENSE_TO_BLACK';
export const CHANGE_COLOR_IN_SEQUENSE_TO_DARKGRAY = 'CHANGE_COLOR_IN_SEQUENSE_TO_DARKGRAY';
export const SET_USER_SEQUENCE = 'SET_USER_SEQUENCE';
