export const GET_EXPENSES_DATA = 'GET_EXPENSES_DATA';
export const SUCCESS_EXPENSES_RESPONSE = 'SUCCESS_EXPENSES_RESPONSE';
export const ERROR_EXPENSES_REQUEST = 'ERROR_EXPENSES_REQUEST';
export const UPDATE_EXISTING_EXPENSES_CATEGORY = 'UPDATE_EXISTING_EXPENSES_CATEGORY';
